companies:
  - ticker: NBIS
    cik: 0001513845
    name: Nebius Group
    filing_types:
      - 20-F
      - 6-K
    is_foreign_private_issuer: true
  - ticker: BE
    cik: '0001664703'
    name: Bloom Energy
    filing_types:
      - 10-K
      - 10-Q
      - 8-K
    is_foreign_private_issuer: false
  - ticker: RDDT
    cik: '0001713445'
    name: Reddit
    filing_types:
      - 10-K
      - 10-Q
      - 8-K
    is_foreign_private_issuer: false
  - ticker: GOOGL
    cik: '0001652044'
    name: Alphabet Inc.
    filing_types:
      - 10-K
      - 10-Q
      - 8-K
    is_foreign_private_issuer: false
  - ticker: MSFT
    cik: 0000789019
    name: MICROSOFT CORP
    filing_types:
      - 10-K
      - 10-Q
      - 8-K
    is_foreign_private_issuer: false
  - ticker: AMZN
    cik: 0001018724
    name: AMAZON COM INC
    filing_types:
      - 10-K
      - 10-Q
      - 8-K
    is_foreign_private_issuer: false
  - ticker: META
    cik: 0001326801
    name: Meta Platforms, Inc.
    filing_types:
      - 10-K
      - 10-Q
      - 8-K
    is_foreign_private_issuer: false
  - ticker: NVDA
    cik: 0001045810
    name: NVIDIA CORP
    filing_types:
      - 10-K
      - 10-Q
      - 8-K
    is_foreign_private_issuer: false
  - ticker: AAPL
    cik: 0000320193
    name: Apple Inc.
    filing_types:
      - 10-K
      - 10-Q
      - 8-K
    is_foreign_private_issuer: false
  - ticker: TSLA
    cik: 0001318605
    name: Tesla, Inc.
    filing_types:
      - 10-K
      - 10-Q
      - 8-K
    is_foreign_private_issuer: false
  - ticker: MU
    cik: '0000723125'
    name: MICRON TECHNOLOGY INC
    filing_types:
      - 10-K
      - 10-Q
      - 8-K
    is_foreign_private_issuer: false
  - ticker: AMD
    cik: 0000002488
    name: ADVANCED MICRO DEVICES INC
    filing_types:
      - 10-K
      - 10-Q
      - 8-K
    is_foreign_private_issuer: false
  - ticker: TSM
    cik: 0001046179
    name: TAIWAN SEMICONDUCTOR MANUFACTURING CO LTD
    filing_types:
      - 20-F
      - 6-K
    is_foreign_private_issuer: true
  - ticker: VRT
    cik: '0001674101'
    name: Vertiv Holdings Co
    filing_types:
      - 10-K
      - 10-Q
      - 8-K
    is_foreign_private_issuer: false
  - ticker: CRWV
    cik: 0001769628
    name: CoreWeave, Inc.
    filing_types:
      - 10-K
      - 10-Q
      - 8-K
    is_foreign_private_issuer: false
  - ticker: IREN
    cik: 0001878848
    name: IREN Ltd
    filing_types:
      - 10-K
      - 10-Q
      - 8-K
    is_foreign_private_issuer: false
  - ticker: AAOI
    cik: '0001158114'
    name: APPLIED OPTOELECTRONICS, INC.
    filing_types:
      - 10-K
      - 10-Q
      - 8-K
    is_foreign_private_issuer: false
  - ticker: ACN
    cik: '0001467373'
    name: Accenture plc
    filing_types:
      - 10-K
      - 10-Q
      - 8-K
    is_foreign_private_issuer: false
  - ticker: AEHR
    cik: '0001040470'
    name: AEHR TEST SYSTEMS
    filing_types:
      - 10-K
      - 10-Q
      - 8-K
    is_foreign_private_issuer: false
  - ticker: ALAB
    cik: '0001736297'
    name: Astera Labs, Inc.
    filing_types:
      - 10-K
      - 10-Q
      - 8-K
    is_foreign_private_issuer: false
  - ticker: ANET
    cik: '0001596532'
    name: Arista Networks, Inc.
    filing_types:
      - 10-K
      - 10-Q
      - 8-K
    is_foreign_private_issuer: false
  - ticker: APP
    cik: '0001751008'
    name: AppLovin Corp
    filing_types:
      - 10-K
      - 10-Q
      - 8-K
    is_foreign_private_issuer: false
  - ticker: ARRY
    cik: '0001820721'
    name: Array Technologies, Inc.
    filing_types:
      - 10-K
      - 10-Q
      - 8-K
    is_foreign_private_issuer: false
  - ticker: AVGO
    cik: '0001730168'
    name: Broadcom Inc.
    filing_types:
      - 10-K
      - 10-Q
      - 8-K
    is_foreign_private_issuer: false
  - ticker: BRUN
    cik: '0002090646'
    name: Boost Run Inc.
    filing_types:
      - 10-K
      - 10-Q
      - 8-K
    is_foreign_private_issuer: false
  - ticker: CEG
    cik: '0001868275'
    name: Constellation Energy Corp
    filing_types:
      - 10-K
      - 10-Q
      - 8-K
    is_foreign_private_issuer: false
  - ticker: COHR
    cik: '0000820318'
    name: COHERENT CORP.
    filing_types:
      - 10-K
      - 10-Q
      - 8-K
    is_foreign_private_issuer: false
  - ticker: COIN
    cik: '0001679788'
    name: Coinbase Global, Inc.
    filing_types:
      - 10-K
      - 10-Q
      - 8-K
    is_foreign_private_issuer: false
  - ticker: CRCL
    cik: '0001876042'
    name: Circle Internet Group, Inc.
    filing_types:
      - 10-K
      - 10-Q
      - 8-K
    is_foreign_private_issuer: false
  - ticker: CRDO
    cik: '0001807794'
    name: Credo Technology Group Holding Ltd
    filing_types:
      - 10-K
      - 10-Q
      - 8-K
    is_foreign_private_issuer: false
  - ticker: DASH
    cik: '0001792789'
    name: DoorDash, Inc.
    filing_types:
      - 10-K
      - 10-Q
      - 8-K
    is_foreign_private_issuer: false
  - ticker: DLO
    cik: '0001846832'
    name: dLocal Ltd
    filing_types:
      - 20-F
      - 6-K
    is_foreign_private_issuer: true
  - ticker: DLR
    cik: '0001297996'
    name: DIGITAL REALTY TRUST, INC.
    filing_types:
      - 10-K
      - 10-Q
      - 8-K
    is_foreign_private_issuer: false
  - ticker: ENPH
    cik: '0001463101'
    name: Enphase Energy, Inc.
    filing_types:
      - 10-K
      - 10-Q
      - 8-K
    is_foreign_private_issuer: false
  - ticker: EQIX
    cik: '0001101239'
    name: EQUINIX INC
    filing_types:
      - 10-K
      - 10-Q
      - 8-K
    is_foreign_private_issuer: false
  - ticker: ETN
    cik: '0001551182'
    name: Eaton Corp plc
    filing_types:
      - 10-K
      - 10-Q
      - 8-K
    is_foreign_private_issuer: false
  - ticker: FIGR
    cik: '0002064124'
    name: Figure Technology Solutions, Inc.
    filing_types:
      - 10-K
      - 10-Q
      - 8-K
    is_foreign_private_issuer: false
  - ticker: FSLR
    cik: '0001274494'
    name: FIRST SOLAR, INC.
    filing_types:
      - 10-K
      - 10-Q
      - 8-K
    is_foreign_private_issuer: false
  - ticker: GEV
    cik: '0001996810'
    name: GE Vernova Inc.
    filing_types:
      - 10-K
      - 10-Q
      - 8-K
    is_foreign_private_issuer: false
  - ticker: HOOD
    cik: '0001783879'
    name: Robinhood Markets, Inc.
    filing_types:
      - 10-K
      - 10-Q
      - 8-K
    is_foreign_private_issuer: false
  - ticker: KEYS
    cik: '0001601046'
    name: Keysight Technologies, Inc.
    filing_types:
      - 10-K
      - 10-Q
      - 8-K
    is_foreign_private_issuer: false
  - ticker: LITE
    cik: '0001633978'
    name: Lumentum Holdings Inc.
    filing_types:
      - 10-K
      - 10-Q
      - 8-K
    is_foreign_private_issuer: false
  - ticker: MELI
    cik: '0001099590'
    name: MERCADOLIBRE INC
    filing_types:
      - 10-K
      - 10-Q
      - 8-K
    is_foreign_private_issuer: false
  - ticker: MRVL
    cik: '0001835632'
    name: Marvell Technology, Inc.
    filing_types:
      - 10-K
      - 10-Q
      - 8-K
    is_foreign_private_issuer: false
  - ticker: MSTR
    cik: '0001050446'
    name: Strategy Inc
    filing_types:
      - 10-K
      - 10-Q
      - 8-K
    is_foreign_private_issuer: false
  - ticker: NOW
    cik: '0001373715'
    name: ServiceNow, Inc.
    filing_types:
      - 10-K
      - 10-Q
      - 8-K
    is_foreign_private_issuer: false
  - ticker: NTNX
    cik: '0001618732'
    name: Nutanix, Inc.
    filing_types:
      - 10-K
      - 10-Q
      - 8-K
    is_foreign_private_issuer: false
  - ticker: NVTS
    cik: '0001821769'
    name: Navitas Semiconductor Corp
    filing_types:
      - 10-K
      - 10-Q
      - 8-K
    is_foreign_private_issuer: false
  - ticker: NXT
    cik: '0001852131'
    name: Nextpower Inc.
    filing_types:
      - 10-K
      - 10-Q
      - 8-K
    is_foreign_private_issuer: false
  - ticker: OKLO
    cik: '0001849056'
    name: Oklo Inc.
    filing_types:
      - 10-K
      - 10-Q
      - 8-K
    is_foreign_private_issuer: false
  - ticker: ORCL
    cik: '0001341439'
    name: ORACLE CORP
    filing_types:
      - 10-K
      - 10-Q
      - 8-K
    is_foreign_private_issuer: false
  - ticker: PINS
    cik: '0001506293'
    name: PINTEREST, INC.
    filing_types:
      - 10-K
      - 10-Q
      - 8-K
    is_foreign_private_issuer: false
  - ticker: POWL
    cik: '0000080420'
    name: POWELL INDUSTRIES INC
    filing_types:
      - 10-K
      - 10-Q
      - 8-K
    is_foreign_private_issuer: false
  - ticker: PWR
    cik: '0001050915'
    name: QUANTA SERVICES, INC.
    filing_types:
      - 10-K
      - 10-Q
      - 8-K
    is_foreign_private_issuer: false
  - ticker: RUN
    cik: '0001469367'
    name: Sunrun Inc.
    filing_types:
      - 10-K
      - 10-Q
      - 8-K
    is_foreign_private_issuer: false
  - ticker: SAP
    cik: '0001000184'
    name: SAP SE
    filing_types:
      - 20-F
      - 6-K
    is_foreign_private_issuer: true
  - ticker: SE
    cik: '0001703399'
    name: Sea Ltd
    filing_types:
      - 20-F
      - 6-K
    is_foreign_private_issuer: true
  - ticker: SEI
    cik: '0001697500'
    name: Solaris Energy Infrastructure, Inc.
    filing_types:
      - 10-K
      - 10-Q
      - 8-K
    is_foreign_private_issuer: false
  - ticker: SHLS
    cik: '0001831651'
    name: Shoals Technologies Group, Inc.
    filing_types:
      - 10-K
      - 10-Q
      - 8-K
    is_foreign_private_issuer: false
  - ticker: SHOP
    cik: '0001594805'
    name: SHOPIFY INC.
    filing_types:
      - 10-K
      - 10-Q
      - 8-K
    is_foreign_private_issuer: false
  - ticker: SMCI
    cik: '0001375365'
    name: Super Micro Computer, Inc.
    filing_types:
      - 10-K
      - 10-Q
      - 8-K
    is_foreign_private_issuer: false
  - ticker: SMR
    cik: '0001822966'
    name: NUSCALE POWER Corp
    filing_types:
      - 10-K
      - 10-Q
      - 8-K
    is_foreign_private_issuer: false
  - ticker: SMTC
    cik: '0000088941'
    name: SEMTECH CORP
    filing_types:
      - 10-K
      - 10-Q
      - 8-K
    is_foreign_private_issuer: false
  - ticker: SNAP
    cik: '0001564408'
    name: Snap Inc
    filing_types:
      - 10-K
      - 10-Q
      - 8-K
    is_foreign_private_issuer: false
  - ticker: SNDK
    cik: '0002023554'
    name: Sandisk Corp
    filing_types:
      - 10-K
      - 10-Q
      - 8-K
    is_foreign_private_issuer: false
  - ticker: TMDX
    cik: '0001756262'
    name: TransMedics Group, Inc.
    filing_types:
      - 10-K
      - 10-Q
      - 8-K
    is_foreign_private_issuer: false
  - ticker: TTD
    cik: '0001671933'
    name: Trade Desk, Inc.
    filing_types:
      - 10-K
      - 10-Q
      - 8-K
    is_foreign_private_issuer: false
  - ticker: TWLO
    cik: '0001447669'
    name: TWILIO INC
    filing_types:
      - 10-K
      - 10-Q
      - 8-K
    is_foreign_private_issuer: false
  - ticker: U
    cik: '0001810806'
    name: Unity Software Inc.
    filing_types:
      - 10-K
      - 10-Q
      - 8-K
    is_foreign_private_issuer: false
  - ticker: VIAV
    cik: '0000912093'
    name: VIAVI SOLUTIONS INC.
    filing_types:
      - 10-K
      - 10-Q
      - 8-K
    is_foreign_private_issuer: false
  - ticker: VICR
    cik: '0000751978'
    name: VICOR CORP
    filing_types:
      - 10-K
      - 10-Q
      - 8-K
    is_foreign_private_issuer: false
  - ticker: VST
    cik: '0001692819'
    name: Vistra Corp.
    filing_types:
      - 10-K
      - 10-Q
      - 8-K
    is_foreign_private_issuer: false
  - ticker: WDC
    cik: '0000106040'
    name: WESTERN DIGITAL CORP
    filing_types:
      - 10-K
      - 10-Q
      - 8-K
    is_foreign_private_issuer: false
